// backend/src/routes/security.routes.js
// Enterprise Security Firewall — Completed v5
// Public Risk Engine • Session Monitor • Compliance Layer • Escalation Engine

const express = require("express");
const router = express.Router();

const { authRequired } = require("../middleware/auth");
const users = require("../users/user.service");
const { readDb, writeDb } = require("../lib/db");
const { getActiveSessionCount } = require("../lib/sessionStore");

/* =========================================================
   ROLE HELPERS
========================================================= */

const ROLES = users?.ROLES || {};
const ADMIN_ROLE = (ROLES.ADMIN || "Admin").toLowerCase();

function normalizeArray(v) {
  if (!v) return [];
  if (Array.isArray(v)) return v;
  return Object.values(v);
}

function isAdmin(role) {
  return String(role || "").toLowerCase() === ADMIN_ROLE;
}

/* =========================================================
   PUBLIC DEVICE RISK (NO AUTH)
========================================================= */

router.post("/public-device-risk", (req, res) => {
  try {
    const { userAgent, language, timezone } = req.body || {};

    let riskScore = 10;

    if (!userAgent) riskScore += 20;
    if (!language) riskScore += 10;
    if (!timezone) riskScore += 10;

    if (String(userAgent).toLowerCase().includes("headless")) {
      riskScore += 40;
    }

    riskScore = Math.min(100, riskScore);

    let level = "Low";
    if (riskScore > 60) level = "High";
    else if (riskScore > 30) level = "Medium";

    return res.json({
      ok: true,
      riskScore,
      level
    });

  } catch {
    res.status(500).json({ ok: false });
  }
});

/* =========================================================
   AUTH REQUIRED BELOW THIS LINE
========================================================= */

router.use(authRequired);

/* =========================================================
   AUTO ESCALATION ENGINE
========================================================= */

function autoEscalateIfNeeded(db, event, req) {
  if (event.severity !== "critical") return;

  const existing = (db.incidents || []).find(
    (i) => i.sourceEventId === event.id
  );

  if (existing) return;

  const newIncident = {
    id: Date.now().toString(),
    title: `AUTO: ${event.title || "Critical Security Event"}`,
    description: event.description || "",
    severity: "critical",
    status: "open",
    sourceEventId: event.id,
    autoGenerated: true,
    companyId: event.companyId || null,
    createdAt: new Date().toISOString(),
  };

  if (!db.incidents) db.incidents = [];
  db.incidents.push(newIncident);
  event.incidentId = newIncident.id;

  writeDb(db);

  const broadcast = req.app.get("broadcastSecurityEvent");
  if (broadcast) broadcast(event);
}

/* =========================================================
   POSTURE SUMMARY
========================================================= */

router.get("/posture-summary", (req, res) => {
  try {
    const db = readDb();

    const companiesArr = normalizeArray(db.companies);
    const usersArr = normalizeArray(db.users);
    const vulnerabilitiesArr = normalizeArray(db.vulnerabilities);
    const incidentsArr = normalizeArray(db.incidents);

    let scopedCompanies = [];
    let scopedUsers = [];
    let scopedVulns = [];

    if (isAdmin(req.user.role)) {
      scopedCompanies = companiesArr;
      scopedUsers = usersArr;
      scopedVulns = vulnerabilitiesArr;
    } else {
      const companyId = req.user.companyId;
      scopedCompanies = companiesArr.filter(c => c.id === companyId);
      scopedUsers = usersArr.filter(u => u.companyId === companyId);
      scopedVulns = vulnerabilitiesArr.filter(v => v.companyId === companyId);
    }

    const critical = scopedVulns.filter(v => v.severity === "critical").length;
    const high = scopedVulns.filter(v => v.severity === "high").length;
    const medium = scopedVulns.filter(v => v.severity === "medium").length;
    const low = scopedVulns.filter(v => v.severity === "low").length;

    let riskScore = 100 - (critical * 15 + high * 8 + medium * 4 + low);
    riskScore = Math.max(5, Math.min(100, riskScore));

    let complianceScore = 100 - (critical * 10 + high * 6 + medium * 3);
    complianceScore = Math.max(10, Math.min(100, complianceScore));

    res.json({
      ok: true,
      scope: isAdmin(req.user.role) ? "global" : "company",
      totalCompanies: scopedCompanies.length,
      totalUsers: scopedUsers.length,
      incidents: incidentsArr.length,
      riskScore: Math.round(riskScore),
      complianceScore: Math.round(complianceScore),
      critical,
      high,
      medium,
      low,
      timestamp: Date.now(),
    });

  } catch {
    res.status(500).json({ ok: false, error: "Failed to generate posture summary" });
  }
});

/* =========================================================
   COMPLIANCE SUMMARY
========================================================= */

router.get("/compliance", (req, res) => {
  try {
    const db = readDb();
    const vulns = db.vulnerabilities || [];

    const critical = vulns.filter(v => v.severity === "critical").length;
    const high = vulns.filter(v => v.severity === "high").length;

    let complianceScore = 100 - (critical * 10 + high * 5);
    complianceScore = Math.max(10, Math.min(100, complianceScore));

    res.json({
      ok: true,
      complianceScore,
      critical,
      high
    });

  } catch {
    res.status(500).json({ ok: false, error: "Compliance failed" });
  }
});

/* =========================================================
   ACTIVE SESSIONS
========================================================= */

router.get("/sessions", (req, res) => {
  try {
    const count = getActiveSessionCount(req.user.id);

    res.json({
      ok: true,
      activeSessions: count
    });

  } catch {
    res.status(500).json({ ok: false, error: "Failed to load sessions" });
  }
});

/* =========================================================
   SECURITY EVENTS
========================================================= */

router.get("/events", (req, res) => {
  try {
    const db = readDb();
    const limit = Number(req.query.limit) || 50;

    let eventsArr = normalizeArray(db.securityEvents);

    if (!isAdmin(req.user.role)) {
      eventsArr = eventsArr.filter(
        e => e.companyId === req.user.companyId
      );
    }

    const events = eventsArr.slice(-limit).reverse();

    res.json({ ok: true, events });

  } catch {
    res.status(500).json({ ok: false, error: "Failed to load events" });
  }
});

/* =========================================================
   CREATE SECURITY EVENT
========================================================= */

router.post("/events", (req, res) => {
  try {
    const db = readDb();
    if (!db.securityEvents) db.securityEvents = [];

    const { title, description, severity = "low" } = req.body;

    const newEvent = {
      id: Date.now().toString(),
      title,
      description: description || "",
      severity,
      acknowledged: false,
      companyId: req.user.companyId || null,
      createdAt: new Date().toISOString(),
    };

    db.securityEvents.push(newEvent);

    autoEscalateIfNeeded(db, newEvent, req);

    writeDb(db);

    const broadcast = req.app.get("broadcastSecurityEvent");
    if (broadcast) broadcast(newEvent);

    res.status(201).json({
      ok: true,
      event: newEvent,
    });

  } catch {
    res.status(500).json({ ok: false, error: "Failed to create event" });
  }
});

/* =========================================================
   VULNERABILITIES
========================================================= */

router.get("/vulnerabilities", (req, res) => {
  try {
    const db = readDb();
    res.json({
      ok: true,
      vulnerabilities: db.vulnerabilities || []
    });
  } catch {
    res.status(500).json({ ok: false, error: "Failed to load vulnerabilities" });
  }
});

module.exports = router;
