const express = require("express");
const router = express.Router();

const { authRequired, requireRole } = require("../middleware/auth");
const users = require("../users/user.service");
const securityTools = require("../services/securityTools");
const { readDb, writeDb } = require("../lib/db");

router.use(authRequired);

/* =========================================================
   ROLE FALLBACKS
========================================================= */

const ROLES = users?.ROLES || {};
const ADMIN_ROLE = (ROLES.ADMIN || "Admin").toLowerCase();

function normalizeArray(v) {
  if (!v) return [];
  if (Array.isArray(v)) return v;
  return Object.values(v);
}

function isAdmin(role) {
  return String(role || "").toLowerCase() === ADMIN_ROLE;
}

/* =========================================================
   AUTO ESCALATION ENGINE
========================================================= */

function autoEscalateIfNeeded(db, event, req) {
  if (event.severity !== "critical") return;

  const existing = (db.incidents || []).find(
    (i) => i.sourceEventId === event.id
  );

  if (existing) return;

  const newIncident = {
    id: Date.now().toString(),
    title: `AUTO: ${event.title || "Critical Security Event"}`,
    description: event.description || "",
    severity: "critical",
    status: "open",
    sourceEventId: event.id,
    autoGenerated: true,
    companyId: event.companyId || null,
    createdAt: new Date().toISOString(),
  };

  if (!db.incidents) db.incidents = [];
  db.incidents.push(newIncident);
  event.incidentId = newIncident.id;

  const broadcast = req.app.get("broadcastSecurityEvent");
  if (broadcast) broadcast(event);
}

/* =========================================================
   POSTURE SUMMARY
========================================================= */

router.get("/posture-summary", (req, res) => {
  try {
    const db = readDb();

    const companiesArr = normalizeArray(db.companies);
    const usersArr = normalizeArray(db.users);
    const vulnerabilitiesArr = normalizeArray(db.vulnerabilities);
    const incidentsArr = normalizeArray(db.incidents);

    let scopedCompanies = [];
    let scopedUsers = [];
    let scopedVulns = [];

    if (isAdmin(req.user.role)) {
      scopedCompanies = companiesArr;
      scopedUsers = usersArr;
      scopedVulns = vulnerabilitiesArr;
    } else {
      const companyId = req.user.companyId;
      scopedCompanies = companiesArr.filter(c => c.id === companyId);
      scopedUsers = usersArr.filter(u => u.companyId === companyId);
      scopedVulns = vulnerabilitiesArr.filter(v => v.companyId === companyId);
    }

    const critical = scopedVulns.filter(v => v.severity === "critical").length;
    const high = scopedVulns.filter(v => v.severity === "high").length;
    const medium = scopedVulns.filter(v => v.severity === "medium").length;
    const low = scopedVulns.filter(v => v.severity === "low").length;

    let riskScore = 100 - (critical * 15 + high * 8 + medium * 4 + low);
    riskScore = Math.max(5, Math.min(100, riskScore));

    let complianceScore = 100 - (critical * 10 + high * 6 + medium * 3);
    complianceScore = Math.max(10, Math.min(100, complianceScore));

    res.json({
      ok: true,
      scope: isAdmin(req.user.role) ? "global" : "company",
      totalCompanies: scopedCompanies.length,
      totalUsers: scopedUsers.length,
      incidents: incidentsArr.length,
      riskScore: Math.round(riskScore),
      complianceScore: Math.round(complianceScore),
      critical,
      high,
      medium,
      low,
      timestamp: Date.now(),
    });

  } catch {
    res.status(500).json({ ok: false, error: "Failed to generate posture summary" });
  }
});

/* =========================================================
   POSTURE CHECKS (NEW – prevents 404)
========================================================= */

router.get("/posture-checks", (req, res) => {
  res.json({
    ok: true,
    checks: []
  });
});

/* =========================================================
   POSTURE RECENT (NEW – prevents 404)
========================================================= */

router.get("/posture-recent", (req, res) => {
  try {
    const db = readDb();
    const limit = Number(req.query.limit) || 20;

    const recent = (db.securityEvents || [])
      .slice(-limit)
      .reverse();

    res.json({
      ok: true,
      recent
    });

  } catch {
    res.status(500).json({ ok: false, error: "Failed to load recent posture data" });
  }
});

/* =========================================================
   VULNERABILITIES (NEW – prevents 404)
========================================================= */

router.get("/vulnerabilities", (req, res) => {
  try {
    const db = readDb();
    res.json({
      ok: true,
      vulnerabilities: db.vulnerabilities || []
    });
  } catch {
    res.status(500).json({ ok: false, error: "Failed to load vulnerabilities" });
  }
});

/* =========================================================
   SECURITY EVENTS
========================================================= */

router.get("/events", (req, res) => {
  try {
    const db = readDb();
    const limit = Number(req.query.limit) || 50;

    let eventsArr = normalizeArray(db.securityEvents);

    if (!isAdmin(req.user.role)) {
      eventsArr = eventsArr.filter(
        e => e.companyId === req.user.companyId
      );
    }

    const events = eventsArr.slice(-limit).reverse();

    res.json({ ok: true, events });

  } catch {
    res.status(500).json({ ok: false, error: "Failed to load events" });
  }
});

/* =========================================================
   CREATE SECURITY EVENT
========================================================= */

router.post("/events", (req, res) => {
  try {
    const db = readDb();
    if (!db.securityEvents) db.securityEvents = [];

    const { title, description, severity = "low" } = req.body;

    const newEvent = {
      id: Date.now().toString(),
      title,
      description: description || "",
      severity,
      acknowledged: false,
      companyId: req.user.companyId || null,
      createdAt: new Date().toISOString(),
    };

   
